config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  root to: 'pages#home'
  get 'plants/index'
  get 'plants/show'
  get 'plants/new'
  get 'plants/create'
  get 'users/show'
  namespace :owner do
    resources :bookings, only: [:index]
  end
  resources :plants, only: [:index, :new, :create, :show] do
    resources :bookings, only: [:new, :create, :index]
    end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  patch 'owner/bookings/:id', to: 'owner/bookings#accept_booking', as: 'owner_accept_booking'
  patch 'owner/bookings/:id', to: 'owner/bookings#refuse_booking', as: 'owner_refuse_booking'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :plant
  before_validation :set_price
  validates :start_date, :end_date, presence: true

  def set_price
    self.total_days = (end_date.to_date - start_date.to_date).to_i
    self.total_price = total_days * plant.price_per_day
  end

  def accept
    self.status = "Accepted"
  end

  def refuse
    self.status = "Refused"
  end
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  #enum sun: {ombre: 1, peu_ensoleille: 2, ensoleille: 3}
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :name, :address ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  has_one_attached :photo
  has_many :bookings
  has_many :plants
  has_many :rented_plants, through: :bookings, source: :plant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private
  
  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)|(^plants$)|(^bookings$)|(^owner\/bookings$)|(^users$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit update destroy]

  def index
    @bookings = Booking.all
  end

  def show
    @plant = Plant.new
  end

  def new
    @booking = Booking.new
    @plant = Plant.find(params[:plant_id])
  end

  def edit
  end

  def create
    @booking = Booking.new(booking_params)
    @plant = Plant.find(params[:plant_id])
    @booking.plant = @plant
    @booking.user = current_user
    @booking.status = "Pending"

    if @booking.save
      redirect_to plants_index_path, notice: "booking was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @booking.update(booking_params)
      redirect_to @booking, notice: "booking was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_url, notice: "booking was successfully destroyed."
  end

  private

  def set_booking
    @plant = Plant.find(params[:id])
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

    

app/controllers/owner/bookings_controller.rb
class Owner::BookingsController < ApplicationController
  before_action :set_booking, only: [:accept, :refuse]

  def index
    @bookings = current_user.bookings.order(created_at: :desc)
    @booked = Booking.joins(:plant).where(plants: {user: current_user}).order(created_at: :desc)
  end

  def accept_booking
    @booking = Booking.find(params[:id])
    @booking.accept
    @booking.save
    redirect_to owner_bookings_path
  end

  def refuse_booking
    @booking = Booking.find(params[:id])
    @booking.refuse
    @booking.save
    redirect_to owner_bookings_path
  end

  def new
    @plant = Plant.find(params[:plant_id])
    @booking = Booking.new(plant_id:@plant.id)
  end

  def create
    @booking = Booking.new(booking_params)
    @plant = Plant.find(params[:plant_id])
    @booking.user = current_user
    @booking.plant = @plant
    @booking.accepted = "Pending"
    @booking.save ? (redirect_to bookings_path(@plant)) : (render :new)
    flash[:notice] = "You have successfully booked a plant"
  end

  private
  def set_booking
    @plant = Plant.find(params[:id])
    @booking = Booking.find(params[:id])
  end

  def save_booking
    @booking.save ? (redirect_to bookings_path) : (render :new)
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :id, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [:show]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      @plants = Plant.global_search(params[:query])
      @markers = @plants.geocoded.map do |plant|
        {
          lat: plant.latitude,
          lng: plant.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { plant: plant })
        }
      end
    else
      @plants = Plant.all
      @markers = @plants.geocoded.map do |plant|
        {
          lat: plant.latitude,
          lng: plant.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { plant: plant })
        }
      end
    end
  end

  def new
    @plant = Plant.new
  end

  def create
    @user = current_user
    @plant = Plant.new(plant_params)
    @plant.user = @user
    if @plant.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @booking = Booking.new
    @plant = Plant.find(params[:id])
  end


  private

  def set_plant
    @plant = Plant.find(params[:id])
  end

  def plant_params
    params.require(:plant).permit(:name, :address, :category, :sun, :description, :price_per_day, :orientation, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @plants = current_user.plants.order(created_at: :desc)
    @myplants = Plant.joins(:plant).where(plants: {user: current_user}).order(created_at: :desc)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<br>
<br>
<br>
<br>
<div class="container-md">
  <div class="row-new">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Book a plant</h3>
          <%= simple_form_for [@plant, @booking] do |f| %>
            <%= f.input :start_date, as: :date, html5: true %>
            <%= f.input :end_date, as: :date, html5: true %>            
            <%= f.submit 'Book this plant', class: 'btn btn-success' %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<br>
<br>
<br>
<br>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4));">
  <div class="container">
    <h1><%= @booking.name %></h1>
  </div>
</div>

<div class="container my-5">
  <div class="cards">
    <% @booking.plants.each do |plant| %>

      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.ravissant-jardin.com/wp-content/uploads/2018/04/physalis-chinese-lanterns.jpg)">
        <%= plant.name %>
        <%= link_to plant_path(plant), method: :delete, data: { confirm: "Are you sure?"}, class: "remove" do %>
          <i class="fas fa-trash"></i>
        <% end %>

        <div class="card-tags">
          <% plant.tags.each do |tag| %>
            <span><%= tag.name %></span>
          <% end %>
          <%= link_to "+", new_plant_plant_tag_path(plant) %>
        </div>

      </div>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="col-4 offset-4">
    <h4>Add a plant</h4>
    <%= simple_form_for [@booking, @plant] do |f| %>
      <%= f.input :name, placeholder: "Palm tree" %>
      <%= f.input :image_url, placeholder: "https://some_nice_picture.com" %>
      <%= f.submit "Add", class: "btn btn-primary my-2" %>
    <% end %>
  </div>
</div>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Locawidz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
        <%= link_to root_path, class: "navbar-brand" do %>
          <%= image_tag("green-weed.png") %>
        <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="search">
        <%= form_tag plants_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "searchTerm",
            placeholder: "Plant Name or localisation"
          %>
          <button type="submit" class="searchButton">
          <i <%= submit_tag "Search", class: "fa fa-search" %></i>
          </button>
        <% end %>
      </div>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a><%= link_to root_path do %>
              <%= content_tag :span, "Home", class:"nav-link" %>
              <% end %>
            </a>
          </li>
          <li class="nav-item">
          <% if current_user == nil %>
            <a><%= link_to new_user_session_path do %>
              <%= content_tag :span, "My profile", class:"nav-link" %>
              <% end %>
            </a>
            <% else %>
            <a><%= link_to user_path(current_user) do %>
              <%= content_tag :span, "My profile", class:"nav-link" %>
              <% end %>
            </a> 
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to new_plant_path do %>
                <%= content_tag :span, "Post a plant", :class => "dropdown-item" %>
              <% end %>
              <%= link_to owner_bookings_path do %>
                <%= content_tag :span, "All my reservations", :class => "dropdown-item" %>
              <% end %>
              <%= link_to new_user_session_path do %>
                <%= content_tag :span, "Connexion", :class => "dropdown-item" %>
              <% end %>
              <%= link_to new_user_registration_path do %>
                <%= content_tag :span, "Create Profile", :class => "dropdown-item" %>
              <% end %>
            </div>
          </li>
        </ul>
      </div>
    </div>

  <%# <div id="custom-container"> %>
    <%= yield %>
  <%# </div>  %>
 
  </body>

  <footer>
  <div class="footer bottom">
      <div class="footer-links">
        <a href="https://www.instagram.com/balcon_fleuri/"><i class="fab fa-instagram"></i></a>
        <a href="https://www.facebook.com/WEED-404093609648112"><i class="fab fa-facebook"></i></a>
      </div>
      <div class="footer-text">
        <p>Locawidz</p>
      </div>
      <div class="footer-copyright">
        Only for plants <i class="fas fa-heart"></i> !
      </div>
  </div>
</footer>

</html>

app/views/owner/bookings/index.html.erb
<br>
<br>
<br>
<br>
<div class="main-container d-flex">

  <div class="container-my-bookings">
    <div class="section-title">
      <h1>My reservations</h1>
    </div>
    <div class="cards-container">
      <p><%= "You don't have a reservation" if @booked.empty? %></p>
      <div class="cards" id="cards-reservation">
        <% @booked.each do |booking| %>
        <div class="card" id="card-reservation" style="width: 18rem;">
          <div class="plant-card-image" id="image-user-plant" style="background-image: url('<%= cl_image_path(booking.plant.photo.key) %>')">
          </div>
        <div class="card-body">
          <div class="card-text">
            <h2><%= booking.plant.name %></h2>
            <p>You have made a reservation for a <strong><%= booking.plant.name %></strong> in <strong><%= booking.plant.category %></strong></p>
            <p><%= booking.plant.description %></p>
          </div>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <div class="btn-flat">Total: <strong><%= booking.total_price%>€</strong></div>
          </li>
          <li class="list-group-item">
            <p>From: <strong><%= booking.start_date.to_date %></strong></p>
            <p>To: <strong><%= booking.end_date.to_date %></strong></p> 
          </li>
          <li class="list-group-item">Take your plant at : 
            <p><%= booking.plant.address %></p>
          </li>
          <li class="list-group-item">Your reservation status is : 
            <p> <%= booking.status %></p>
          </li>
        </ul>
        </div>
      <% end %>
      </div>
    </div>
  </div>
  <div class="container" id="small-container">
  </div>
  <div class="container-booked-plants">
    <div class="section-title">
      <h1>My reserved plants</h1>
    </div>
    <div class="cards-container d-flex">
        <p><%= "No plant request fort the moment" if @bookings.empty? %></p>
        <div class="cards" id="owner-cards-reservation">
        <% @bookings.each do |booking| %>
          <div class="card text-center" id="title-plant-reserved" >
            <div class="card-header">
              <h5><strong><%= booking.plant.name %></strong></h5>
            </div>
            <div class="card-body">
              <h5 class="card-title">Your <strong><%= booking.plant.name %></strong> has just been reserved !</h5>
              <p class="card-text">For a total of :<%= booking.total_price %>€</p>
              <li class="list-group-item"></li>
                <p>From: <strong><%= booking.start_date.to_date %></strong></p>
                <p>To: <strong><%= booking.end_date.to_date %></strong></p> 
              </li>
              <p><strong><%= booking.status %></strong></p>
                <%= link_to 'Accept', owner_accept_booking_path(booking), method: :patch %>
                <%= link_to 'Decline', owner_refuse_booking_path(booking), method: :patch %>
            </div>
          </div>
        <%end%>
        </div>
    </div>
  </div>
</div>

app/views/owner/index.html.erb
<h1> bookings index </h1>

app/views/pages/home.html.erb
<br>
<br>
<br>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/3277932/pexels-photo-3277932.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260);">
  <div class="container" id="home_banner">
    <h1><span id="banner-typed-text"></span></h1><br>
    <p>The best way to rent <strong>flowers easely </strong>! <br><br>
    I want to <%= link_to 'Find plant', plants_index_path,class: 'btn'  %>
    <%= link_to 'Add a plant', new_plant_path,class: 'btn'  %></p>
  </div>
</div>

<%= link_to(plants_index_path) do %>
<div class="cards" id="home-cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.aujourdhui.com/wp-content/uploads/2020/03/Herbes-aromatiques-1000.jpg)">
    Aromatics
  </div>
  
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/serdy-m-dia-inc/image/upload/f_auto/fl_lossy/q_auto:eco/x_0,y_0,w_1279,h_720,c_crop/w_836,h_470,c_scale/v1507088547/foodlavie/prod/recettes/gateau-aux-petits-fruits-et-amandes-sans-cuisson-bddaccf8)">
    Small fruits
  </div>
  
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.le-panier-de-flo.fr/4063-large_default/fleurs-comestibles-bataille-de-fleurs-30-fleurs-la-piece.jpg)">
    Comestible flowers
  </div>

   <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.ctendance.fr/wp-content/uploads/2020/12/vertus-plantes-vertes.jpg)">
    Decoration
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://streetphotographycolor.com/wp-content/uploads/2021/02/cops5-inspiration-blumenfotografie-02-mic.jpg)">
    Healthy
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://jardinierparesseux.com/wp-content/uploads/2019/01/20190125a-www.chhajedgarden.com_.png)">
    Easy-maintenance
  </div>
</div>
<% end %>

app/views/plants/_info_window.html.erb
<h2><%=plant.name%></h2>
<p><%=plant.address%></p>
<p><%=plant.price_per_day%> €/day</p>

app/views/plants/create.html.erb
<h1>Plants#create</h1>
<p>Find me in app/views/plants/create.html.erb</p>

app/views/plants/index.html.erb
<h1>Plants#index</h1>
<p>Find me in app/views/plants/index.html.erb</p>

<h1 id="index-title">Available plants</h1>

<div class="cards-container">
  <div class="cards">
    <% @plants.each do |plant| %>
      <div class="card">
          <div class="plant-card-image" style="background-image: url('<%= cl_image_path(plant.photo.key)%>')">
          </div>
          <div class="plant-card-content">
            <div class="plant-card-title">
              <h4><%= plant.name %></h4>
            </div>
            <p><%= plant.address %></p>
            <div class="flex">
              <i class="material-icons mr-2"><%= plant.price_per_day %>€/day</i>
            </div>
          </div>
          <div class="plant-card-actions">
            <%= link_to 'More info', plant_path(plant) %>
          </div>
      </div>
    <% end %>
  </div>

  <div id="map"
    style="width: 100%; height: 600px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

</div>

app/views/plants/new.html.erb
<h1>Plants#new</h1>
<p>Find me in app/views/plants/new.html.erb</p>
<div class="container-md">
  <div class="row-new">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add a plant</h3>
          <%= simple_form_for @plant do |f| %>
            <%= f.input :name, placeholder: 'Name of your plant' %>
            <%= f.input :address, id:"plant_address", placeholder: 'Where is your plant ?' %>
            <%= f.input :description, placeholder: 'Enter a description about the plant' %>
            <%= f.input :category, prompt: 'Choose a category', collection: ['Aromatic', 'Small Fruits', 'Comestible flowoer', 'Decoration', 'Healthy', 'Easy-maintenance'] %>
            <%= f.input :price_per_day, placeholder: '€/day' %>
            <%= f.input :orientation, as: :radio_buttons, wrapper_html: {class: 'inline'}, collection: ['North', 'East', 'South', 'West'] %>
            <%= f.input :sun, as: :radio_buttons, class:'form-check-inline', collection: ['Shadow 🌥', 'Sunny 🌞', 'Whatever 🌤'] %>
            <%= f.input :photo, as: :file %>
            <%= f.submit 'Add plant', class: 'btn btn-success' %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/plants/show.html.erb
<br>
<br>
<br>

<div class="row card-product" id="plant_card">

  <div class="col-4">
    <%= cl_image_tag(@plant.photo.key,width: 700, height: 350, crop: :fill) %>
    <%= link_to 'Return', plants_index_path, class: "btn btn-light"  %>
  </div>

  <div class="col-6">
    <div class="mx-2">
      <div class="d-flex justify-content-end">
        <div class="btn-flat"><%= @plant.price_per_day%>€/day</div>
      </div>
      <div>
        <div class="card-product-infos">
          <h2><%= @plant.name %></h2>

          <p><%= @plant.description %>
          <br>
          <br>
            Orientation: <%= @plant.orientation %>
          <br>
          <br>
            Address: <%= @plant.address %>
          </p>
        </div>
      </div>
      <div class="container-lg">
        <div class="row-new">
        
            <div class="bg-white rounded p-3 shadow">
              <h3>Book a plant</h3>
                <%= simple_form_for [@plant, @booking] do |f| %>
                  <%= f.input :start_date, as: :date, html5: true %>
                  <%= f.input :end_date, as: :date, html5: true %>            
                  <%= f.submit 'Book this plant', class: 'btn btn-success' %>
                <% end %>
            </div>
        
        </div>
      </div>
    </div>
  </div>

</div>

app/views/users/new.html.erb
<br>
<br>
<br>
<div class="container-md">
  <div class="row-new">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>New User</h3>
          <%= simple_form_for @user do |f| %>
            <%= f.input :name, placeholder: 'Your full name' %>
            <%= f.input :email, placeholder: 'user@mail.com' %>
            <%= f.input :encrypted_password, placeholder: '9 letters min' %>
            <%= f.input :photo, as: :file %>
            <%= f.submit 'Create profile', class: 'btn btn-success' %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<br>
<br>
<br>
<div class="row card-product" id="plant_card_profile">
  <div class="col-4">
    <p><%= image_tag("avatar.png") if @user.photo.blank? %></p>
    <%= cl_image_tag(@user.photo.key,width: 700, height: 350, crop: :fill) if @user.photo.present? %>
    <%= simple_form_for @user do |f| %>
      <%= f.input :photo, as: :file %>
      <%= f.submit 'Add your photo', class: 'btn btn-success' %>
    <% end %>
  </div>
  
  <div class="col-6">
    <div class="mx-2">
      <div>
      
        <div class="card-product-infos">
          <h2><%= @user.name %></h2>
          <p><%= @user.email %></p>
        </div>

        <div class="container">
          <div class="section-title">
            <h1>My plants</h1>
          </div>
          <div class="cards-container">
              <p><%= "You have no plant fort the moment" if @user.plants.empty? %></p>
              <div class="cards" id="owner-cards-reservation">
                <% @user.plants.each do |plant| %>
                  <div class="card" id="plant-card-index">
                  <div class="plant-card-image" id="image-user-plant" style="background-image: url('<%= cl_image_path(plant.photo.key) %>')">
                    <%#= cl_image_tag(plant.photo.key) %>
                  </div>
                  <div class="plant-card-content">
                    <div class="plant-card-title">
                      <h4><%= plant.name %></h4>
                    </div>
                    <div class="flex">
                      <i class="material-icons mr-2"><%= plant.price_per_day %>€/day</i>
                    </div>
                  </div>
              </div>
              <%end%>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div> 
</div>  